// <auto-generated />
using Gamebook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gamebook.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200105192944_UserId-achievements")]
    partial class UserIdachievements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gamebook.Model.Achievements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BedroomAdventure");

                    b.Property<bool>("CrowbarsAreHeavy");

                    b.Property<bool>("DoNothingAndDie");

                    b.Property<bool>("FallOut");

                    b.Property<bool>("ItsDark");

                    b.Property<bool>("KnifeFight");

                    b.Property<bool>("KungFuFight");

                    b.Property<bool>("PushingNeverWorks");

                    b.Property<bool>("TurnAround");

                    b.Property<int>("UserId");

                    b.Property<bool>("win");

                    b.HasKey("Id");

                    b.ToTable("achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedroomAdventure = false,
                            CrowbarsAreHeavy = false,
                            DoNothingAndDie = false,
                            FallOut = false,
                            ItsDark = false,
                            KnifeFight = false,
                            KungFuFight = false,
                            PushingNeverWorks = false,
                            TurnAround = false,
                            UserId = 0,
                            win = false
                        });
                });

            modelBuilder.Entity("Gamebook.Models.RoomTexts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("linktext1");

                    b.Property<string>("linktext2");

                    b.Property<string>("linktext3");

                    b.Property<string>("text");

                    b.HasKey("Id");

                    b.ToTable("roomTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            linktext1 = "turn around and leave",
                            linktext2 = "Garage",
                            linktext3 = "Hallway",
                            text = "entering house bla bla story"
                        },
                        new
                        {
                            Id = 2,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "you turn around and leave, fuck you house"
                        },
                        new
                        {
                            Id = 3,
                            linktext1 = "yes",
                            linktext2 = "no",
                            linktext3 = "",
                            text = "found crowbar, take it?"
                        },
                        new
                        {
                            Id = 4,
                            linktext1 = "bedroom",
                            linktext2 = "even more hallway",
                            linktext3 = "",
                            text = "cool crowbar, now hall2"
                        },
                        new
                        {
                            Id = 5,
                            linktext1 = "bedroom",
                            linktext2 = "even more hallway",
                            linktext3 = "",
                            text = "bad crowbar, now hall2"
                        },
                        new
                        {
                            Id = 6,
                            linktext1 = "kitchen",
                            linktext2 = "more hallway",
                            linktext3 = "",
                            text = "entering hall, cool af"
                        },
                        new
                        {
                            Id = 7,
                            linktext1 = "yes",
                            linktext2 = "no",
                            linktext3 = "",
                            text = "entering kitchen uwu"
                        },
                        new
                        {
                            Id = 8,
                            linktext1 = "bedroom",
                            linktext2 = "even more hallway",
                            linktext3 = "",
                            text = "taking knife, hall2"
                        },
                        new
                        {
                            Id = 9,
                            linktext1 = "bedroom",
                            linktext2 = "even more hallway",
                            linktext3 = "",
                            text = "byebye knife, hall2"
                        },
                        new
                        {
                            Id = 10,
                            linktext1 = "bedroom",
                            linktext2 = "even more hallway",
                            linktext3 = "",
                            text = "now entering: hall2"
                        },
                        new
                        {
                            Id = 11,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "entering bedroom, this is a fucky wucky"
                        },
                        new
                        {
                            Id = 12,
                            linktext1 = "living room",
                            linktext2 = "Basement",
                            linktext3 = "cool window, check it out",
                            text = "going to hall 3"
                        },
                        new
                        {
                            Id = 13,
                            linktext1 = "yes",
                            linktext2 = "no",
                            linktext3 = "",
                            text = "hello Living room, keep crowbar"
                        },
                        new
                        {
                            Id = 14,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "keep crowbar"
                        },
                        new
                        {
                            Id = 15,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "leave crowbar"
                        },
                        new
                        {
                            Id = 16,
                            linktext1 = "left",
                            linktext2 = "mid",
                            linktext3 = "right",
                            text = "entering kitchen uwu"
                        },
                        new
                        {
                            Id = 17,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "straight into basement"
                        },
                        new
                        {
                            Id = 18,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "cool window, you looked so close that you fell out and died"
                        },
                        new
                        {
                            Id = 19,
                            linktext1 = "run",
                            linktext2 = "fight",
                            linktext3 = "",
                            text = "i have a flashlight, but i see a scawy monstew."
                        },
                        new
                        {
                            Id = 20,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "the crowbar is heavy, can't run, ded"
                        },
                        new
                        {
                            Id = 21,
                            linktext1 = "push",
                            linktext2 = "pull",
                            linktext3 = "",
                            text = "i'm running, but there's a door, push or pull?"
                        },
                        new
                        {
                            Id = 22,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "i'm pushing as hard as i can, i can't get through and die"
                        },
                        new
                        {
                            Id = 23,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "i pulled and it opened, so i ran, closed it behind me and the monster tried to push"
                        },
                        new
                        {
                            Id = 24,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "i'm trying to fight the monster, good thing i got this knife. the monster ripped me apart"
                        },
                        new
                        {
                            Id = 25,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "i'm trying to fight the monster without a knife. the monster ripped me apart"
                        },
                        new
                        {
                            Id = 26,
                            linktext1 = "",
                            linktext2 = "",
                            linktext3 = "",
                            text = "i don't have a flashlight and it's dark. i feel a breath on my back. a monster ripped me apart"
                        });
                });

            modelBuilder.Entity("Gamebook.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("login")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            login = "first",
                            password = "first"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
